-- Drop existing tables if they exist
DROP TABLE IF EXISTS post_likes;
DROP TABLE IF EXISTS comment_likes;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS users;

-- Create tables
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE company (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    parent_company_id INTEGER REFERENCES company(id) ON DELETE SET NULL,
    industry VARCHAR(255),
    sub_industry VARCHAR(255),
    headquarters VARCHAR(255),
    date_incorporated DATE,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
    );

CREATE TABLE post (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    company_id INTEGER NOT NULL REFERENCES company(id) ON DELETE SET NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    likes INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE comment (
    id SERIAL PRIMARY KEY,
    message TEXT NOT NULL,
    post_id INTEGER NOT NULL REFERENCES post(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    likes INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Likes join tables
CREATE TABLE post_likes (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    post_id INTEGER NOT NULL REFERENCES post(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, post_id)
);

CREATE TABLE comment_likes (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id INTEGER NOT NULL REFERENCES comment(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, comment_id)
);

-- Trigger function to keep updated_at current on UPDATE
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER post_set_updated_at
BEFORE UPDATE ON post
FOR EACH ROW
EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER comment_set_updated_at
BEFORE UPDATE ON comment
FOR EACH ROW
EXECUTE FUNCTION trigger_set_updated_at();


INSERT INTO company (name, industry, sub_industry, headquarters, date_incorporated) VALUES
('Fox Corporation(Class B)', 'Communication Services', 'Broadcasting', 'New York City, New York', '2019-03-19'),
('Ameriprise Financial', 'Financials', 'Asset Management & Custody Banks', 'Minneapolis, Minnesota', '2005-10-03'),
('Entergy', 'Utilities', 'Electric Utilities', 'New Orleans, Louisiana', '1957-03-04'),
('AbbVie', 'Health Care', 'Biotechnology', 'North Chicago, Illinois', '2012-12-31'),
('Principal Financial Group', 'Financials', 'Life & Health Insurance', 'Des Moines, Iowa', '2002-07-22'),
('TransDigm Group', 'Industrials', 'Aerospace & Defense', 'Cleveland, Ohio', '2016-06-03'),
('CRH plc', 'Materials', 'Construction Materials', 'Dublin, Ireland', '2025-12-22'),
('Nvidia', 'Information Technology', 'Semiconductors', 'Santa Clara, California', '2001-11-30'),
('Elevance Health', 'Health Care', 'Managed Health Care', 'Indianapolis, Indiana', '2002-07-25'),
('Gartner', 'Information Technology', 'IT Consulting & Other Services', 'Stamford, Connecticut', '2017-04-05'),
('Paycom', 'Industrials', 'Human Resource & Employment Services', 'Oklahoma City, Oklahoma', '2020-01-28'),
('Intercontinental Exchange', 'Financials', 'Financial Exchanges & Data', 'Atlanta, Georgia', '2007-09-26'),
('Chubb Limited', 'Financials', 'Property & Casualty Insurance', 'Zurich, Switzerland', '2010-07-15'),
('HCA Healthcare', 'Health Care', 'Health Care Facilities', 'Nashville, Tennessee', '2015-01-27'),
('Incyte', 'Health Care', 'Biotechnology', 'Wilmington, Delaware', '2017-02-28'),
('O''Reilly Automotive', 'Consumer Discretionary', 'Automotive Retail', 'Springfield, Missouri', '2009-03-27'),
('Arthur J. Gallagher & Co.', 'Financials', 'Insurance Brokers', 'Rolling Meadows, Illinois', '2016-05-31'),
('Interpublic Group of Companies (The)', 'Communication Services', 'Advertising', 'New York City, New York', '1992-10-01'),
('Agilent Technologies', 'Health Care', 'Life Sciences Tools & Services', 'Santa Clara, California', '2000-06-05'),
('Albemarle Corporation', 'Materials', 'Specialty Chemicals', 'Charlotte, North Carolina', '2016-07-01'),
('Vertex Pharmaceuticals', 'Health Care', 'Biotechnology', 'Boston, Massachusetts', '2013-09-23'),
('Sempra', 'Utilities', 'Multi-Utilities', 'San Diego, California', '2017-03-17'),
('Lennox International', 'Industrials', 'Building Products', 'Richardson, Texas', '2024-12-23'),
('Generac', 'Industrials', 'Electrical Components & Equipment', 'Waukesha, Wisconsin', '2021-03-22'),
('Diamondback Energy', 'Energy', 'Oil & Gas Exploration & Production', 'Midland, Texas', '2018-12-03'),
('Cincinnati Financial', 'Financials', 'Property & Casualty Insurance', 'Fairfield, Ohio', '1997-12-18'),
('Mondelez International', 'Consumer Staples', 'Packaged Foods & Meats', 'Chicago, Illinois', '2012-10-02'),
('Republic Services', 'Industrials', 'Environmental & Facilities Services', 'Phoenix, Arizona', '2008-12-05'),
('M&T Bank', 'Financials', 'Regional Banks', 'Buffalo, New York', '2004-02-23'),
('Honeywell', 'Industrials', 'Industrial Conglomerates', 'Charlotte, North Carolina', '1957-03-04'),
('Fortinet', 'Information Technology', 'Systems Software', 'Sunnyvale, California', '2018-10-11'),
('W. R. Berkley Corporation', 'Financials', 'Property & Casualty Insurance', 'Greenwich, Connecticut', '2019-12-05'),
('TE Connectivity', 'Information Technology', 'Electronic Manufacturing Services', 'Galway, Ireland', '2011-10-17'),
('Warner Bros. Discovery', 'Communication Services', 'Broadcasting', 'New York City, New York', '2022-04-11'),
('UnitedHealth Group', 'Health Care', 'Managed Health Care', 'Eden Prairie, Minnesota', '1994-07-01'),
('Exelon', 'Utilities', 'Electric Utilities', 'Chicago, Illinois', '1957-03-04'),
('DoorDash', 'Consumer Discretionary', 'Specialized Consumer Services', 'San Francisco, California', '2025-03-24'),
('PPL Corporation', 'Utilities', 'Electric Utilities', 'Allentown, Pennsylvania', '2001-10-01'),
('Hasbro', 'Consumer Discretionary', 'Leisure Products', 'Pawtucket, Rhode Island', '1984-09-30'),
('DuPont', 'Materials', 'Specialty Chemicals', 'Wilmington, Delaware', '2019-06-03'),
('Boeing', 'Industrials', 'Aerospace & Defense', 'Arlington, Virginia', '1957-03-04'),
('Cooper Companies (The)', 'Health Care', 'Health Care Supplies', 'San Ramon, California', '2016-09-23'),
('Robinhood Markets', 'Financials', 'Investment Banking & Brokerage', 'Menlo Park, California', '2025-09-22'),
('Garmin', 'Consumer Discretionary', 'Consumer Electronics', 'Schaffhausen, Switzerland', '2012-12-12'),
('General Dynamics', 'Industrials', 'Aerospace & Defense', 'Reston, Virginia', '1957-03-04'),
('Lululemon Athletica', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Vancouver, Canada', '2023-10-18'),
('Qnity Electronics', 'Information Technology', 'Semiconductor Materials & Equipment', 'Wilmington, Delaware', '2025-11-03'),
('Stryker Corporation', 'Health Care', 'Health Care Equipment', 'Kalamazoo, Michigan', '2000-12-12'),
('Broadridge Financial Solutions', 'Industrials', 'Data Processing & Outsourced Services', 'Lake Success, New York', '2018-06-18'),
('Carrier Global', 'Industrials', 'Building Products', 'Palm Beach Gardens, Florida', '2020-04-03'),
('Amcor', 'Materials', 'Paper & Plastic Packaging Products & Materials', 'Warmley,Bristol, United Kingdom', '2019-06-07'),
('KKR & Co.', 'Financials', 'Asset Management & Custody Banks', 'New York City, New York', '2024-06-24'),
('Constellation Energy', 'Utilities', 'Electric Utilities', 'Baltimore, Maryland', '2022-02-02'),
('Fair Isaac', 'Information Technology', 'Application Software', 'Bozeman, Montana', '2023-03-20'),
('Philip Morris International', 'Consumer Staples', 'Tobacco', 'New York City, New York', '2008-03-31'),
('Salesforce', 'Information Technology', 'Application Software', 'San Francisco, California', '2008-09-15'),
('Adobe Inc.', 'Information Technology', 'Application Software', 'San Jose, California', '1997-05-05'),
('Walgreens Boots Alliance', 'Consumer Staples', 'Drug Retail', 'Deerfield, Illinois', '1979-12-31'),
('Quest Diagnostics', 'Health Care', 'Health Care Services', 'Secaucus, New Jersey', '2002-12-12'),
('PG&E Corporation', 'Utilities', 'Multi-Utilities', 'Oakland, California', '2022-10-03'),
('Quanta Services', 'Industrials', 'Construction & Engineering', 'Houston, Texas', '2009-07-01'),
('Cummins', 'Industrials', 'Construction Machinery & Heavy Transportation Equipment', 'Columbus, Indiana', '1965-03-31'),
('Centene Corporation', 'Health Care', 'Managed Health Care', 'St. Louis, Missouri', '2016-03-30'),
('Fastenal', 'Industrials', 'Trading Companies & Distributors', 'Winona, Minnesota', '2008-09-15'),
('CME Group', 'Financials', 'Financial Exchanges & Data', 'Chicago, Illinois', '2006-08-11'),
('Humana', 'Health Care', 'Managed Health Care', 'Louisville, Kentucky', '2012-12-10'),
('CrowdStrike', 'Information Technology', 'Systems Software', 'Austin, Texas', '2024-06-24'),
('Solventum', 'Health Care', 'Health Care Technology', 'Saint Paul, Minnesota', '2024-04-01'),
('Host Hotels & Resorts', 'Real Estate', 'Hotel & Resort REITs', 'Bethesda, Maryland', '2007-03-20'),
('Tesla, Inc.', 'Consumer Discretionary', 'Automobile Manufacturers', 'Austin, Texas', '2020-12-21'),
('eBay Inc.', 'Consumer Discretionary', 'Broadline Retail', 'San Jose, California', '2002-07-22'),
('Federal Realty Investment Trust', 'Real Estate', 'Retail REITs', 'Rockville, Maryland', '2016-02-01'),
('Nordson Corporation', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Westlake, Ohio', '2022-02-15'),
('Molson Coors Beverage Company', 'Consumer Staples', 'Brewers', 'Chicago, Illinois', '1976-06-30'),
('Valero Energy', 'Energy', 'Oil & Gas Refining & Marketing', 'San Antonio, Texas', '2002-12-20'),
('Marsh McLennan', 'Financials', 'Insurance Brokers', 'New York City, New York', '1987-08-31'),
('Schlumberger', 'Energy', 'Oil & Gas Equipment & Services', 'Houston, Texas', '1957-03-04'),
('EQT Corporation', 'Energy', 'Oil & Gas Exploration & Production', 'Pittsburgh, Pennsylvania', '2022-10-03'),
('Aptiv', 'Consumer Discretionary', 'Automotive Parts & Equipment', 'Dublin, Ireland', '2012-12-24'),
('Idexx Laboratories', 'Health Care', 'Health Care Equipment', 'Westbrook, Maine', '2017-01-05'),
('Ball Corporation', 'Materials', 'Metal, Glass & Plastic Containers', 'Broomfield, Colorado', '1984-10-31'),
('ResMed', 'Health Care', 'Health Care Equipment', 'San Diego, California', '2017-07-26'),
('Duke Energy', 'Utilities', 'Electric Utilities', 'Charlotte, North Carolina', '1976-06-30'),
('Pinnacle West Capital', 'Utilities', 'Multi-Utilities', 'Phoenix, Arizona', '1999-10-04'),
('GE Aerospace', 'Industrials', 'Aerospace & Defense', 'Evendale, Ohio', '1957-03-04'),
('Colgate-Palmolive', 'Consumer Staples', 'Household Products', 'New York City, New York', '1957-03-04'),
('Costco', 'Consumer Staples', 'Consumer Staples Merchandise Retail', 'Issaquah, Washington', '1993-10-01'),
('Public Storage', 'Real Estate', 'Self-Storage REITs', 'Glendale, California', '2005-08-19'),
('AT&T', 'Communication Services', 'Integrated Telecommunication Services', 'Dallas, Texas', '1983-11-30'),
('NiSource', 'Utilities', 'Multi-Utilities', 'Merrillville, Indiana', '2000-11-02'),
('Occidental Petroleum', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', '1957-03-04'),
('Charles Schwab Corporation', 'Financials', 'Investment Banking & Brokerage', 'Westlake, Texas', '1997-06-02'),
('Akamai Technologies', 'Information Technology', 'Internet Services & Infrastructure', 'Cambridge, Massachusetts', '2007-07-12'),
('Kimco Realty', 'Real Estate', 'Retail REITs', 'Jericho, New York', '2006-04-04'),
('HP Inc.', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'Palo Alto, California', '1974-12-31'),
('Bunge Global', 'Consumer Staples', 'Agricultural Products & Services', 'Chesterfield, Missouri', '2023-03-15'),
('Motorola Solutions', 'Information Technology', 'Communications Equipment', 'Chicago, Illinois', '1957-03-04'),
('Meta Platforms', 'Communication Services', 'Interactive Media & Services', 'Menlo Park, California', '2013-12-23'),
('Lennar', 'Consumer Discretionary', 'Homebuilding', 'Miami, Florida', '2005-10-04'),
('LyondellBasell', 'Materials', 'Specialty Chemicals', 'Rotterdam, Netherlands', '2012-09-05'),
('ExxonMobil', 'Energy', 'Integrated Oil & Gas', 'Irving, Texas', '1957-03-04'),
('Evergy', 'Utilities', 'Electric Utilities', 'Kansas City, Missouri', '2018-06-05'),
('Northrop Grumman', 'Industrials', 'Aerospace & Defense', 'West Falls Church, Virginia[3]', '1957-03-04'),
('Ralph Lauren Corporation', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York City, New York', '2007-02-02'),
('Match Group', 'Communication Services', 'Interactive Media & Services', 'Dallas, Texas', '2021-09-20'),
('CSX Corporation', 'Industrials', 'Rail Transportation', 'Jacksonville, Florida', '1957-03-04'),
('DaVita', 'Health Care', 'Health Care Services', 'Denver, Colorado', '2008-07-31'),
('KLA Corporation', 'Information Technology', 'Semiconductor Materials & Equipment', 'Milpitas, California', '1997-09-30'),
('Cisco', 'Information Technology', 'Communications Equipment', 'San Jose, California', '1993-12-01'),
('Mohawk Industries', 'Consumer Discretionary', 'Home Furnishings', 'Calhoun, Georgia', '2013-12-23'),
('Iron Mountain', 'Real Estate', 'Other Specialized REITs', 'Portsmouth, New Hampshire', '2009-01-06'),
('Allstate', 'Financials', 'Property & Casualty Insurance', 'Northbrook, Illinois', '1995-07-13'),
('Henry Schein', 'Health Care', 'Health Care Distributors', 'Melville, New York', '2015-03-17'),
('Hershey Company (The)', 'Consumer Staples', 'Packaged Foods & Meats', 'Hershey, Pennsylvania', '1957-03-04'),
('Mosaic Company (The)', 'Materials', 'Fertilizers & Agricultural Chemicals', 'Tampa, Florida', '2011-09-26'),
('Verizon', 'Communication Services', 'Integrated Telecommunication Services', 'New York City, New York', '1983-11-30'),
('Packaging Corporation of America', 'Materials', 'Paper & Plastic Packaging Products & Materials', 'Lake Forest, Illinois', '2017-07-26'),
('Delta Air Lines', 'Industrials', 'Passenger Airlines', 'Atlanta, Georgia', '2013-09-11'),
('AES Corporation', 'Utilities', 'Independent Power Producers & Energy Traders', 'Arlington, Virginia', '1998-10-02'),
('Dover Corporation', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Downers Grove, Illinois', '1985-10-31'),
('Verisk Analytics', 'Industrials', 'Research & Consulting Services', 'Jersey City, New Jersey', '2015-10-08'),
('Hubbell Incorporated', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Shelton, Connecticut', '2023-10-18'),
('Digital Realty', 'Real Estate', 'Data Center REITs', 'Austin, Texas', '2016-05-18'),
('Automatic Data Processing', 'Industrials', 'Human Resource & Employment Services', 'Roseland, New Jersey', '1981-03-31'),
('Walmart', 'Consumer Staples', 'Consumer Staples Merchandise Retail', 'Bentonville, Arkansas', '1982-08-31'),
('Tyson Foods', 'Consumer Staples', 'Packaged Foods & Meats', 'Springdale, Arkansas', '2005-08-10'),
('Solstice Advanced Materials', 'Materials', 'Specialty Chemicals', 'Morris Plains, New Jersey', '2025-10-30'),
('Universal Health Services', 'Health Care', 'Health Care Facilities', 'King of Prussia, Pennsylvania', '2014-09-20'),
('Regency Centers', 'Real Estate', 'Retail REITs', 'Jacksonville, Florida', '2017-03-02'),
('Trade Desk (The)', 'Communication Services', 'Advertising', 'Ventura, California', '2025-07-18'),
('Axon Enterprise', 'Industrials', 'Aerospace & Defense', 'Scottsdale, Arizona', '2023-05-04'),
('3M', 'Industrials', 'Industrial Conglomerates', 'Saint Paul, Minnesota', '1957-03-04'),
('Ross Stores', 'Consumer Discretionary', 'Apparel Retail', 'Dublin, California', '2009-12-21'),
('Freeport-McMoRan', 'Materials', 'Copper', 'Phoenix, Arizona', '2011-07-01'),
('Jabil', 'Information Technology', 'Electronic Manufacturing Services', 'St. Petersburg, Florida', '2023-12-18'),
('Intel', 'Information Technology', 'Semiconductors', 'Santa Clara, California', '1976-12-31'),
('Regeneron Pharmaceuticals', 'Health Care', 'Biotechnology', 'Tarrytown, New York', '2013-05-01'),
('Carvana', 'Consumer Discretionary', 'Automotive Retail', 'Tempe, Arizona', '2025-12-22'),
('Targa Resources', 'Energy', 'Oil & Gas Storage & Transportation', 'Houston, Texas', '2022-10-12'),
('Conagra Brands', 'Consumer Staples', 'Packaged Foods & Meats', 'Chicago, Illinois', '1983-08-31'),
('W. W. Grainger', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Lake Forest, Illinois', '1981-06-30'),
('Fiserv', 'Financials', 'Transaction & Payment Processing Services', 'Brookfield, Wisconsin', '2001-04-02'),
('Leidos', 'Industrials', 'Diversified Support Services', 'Reston, Virginia', '2019-08-09'),
('Johnson & Johnson', 'Health Care', 'Pharmaceuticals', 'New Brunswick, New Jersey', '1973-06-30'),
('Thermo Fisher Scientific', 'Health Care', 'Life Sciences Tools & Services', 'Waltham, Massachusetts', '2004-08-03'),
('Veralto', 'Industrials', 'Environmental & Facilities Services', 'Waltham, Massachusetts', '2023-10-02'),
('Hormel Foods', 'Consumer Staples', 'Packaged Foods & Meats', 'Austin, Minnesota', '2009-03-04'),
('Skyworks Solutions', 'Information Technology', 'Semiconductors', 'Irvine, California', '2015-03-12'),
('Altria', 'Consumer Staples', 'Tobacco', 'Richmond, Virginia', '1957-03-04'),
('Paramount Skydance Corporation', 'Communication Services', 'Movies & Entertainment', 'Los Angeles, California', '1994-09-30'),
('Kenvue', 'Consumer Staples', 'Personal Care Products', 'Skillman, New Jersey', '2023-08-25'),
('Revvity', 'Health Care', 'Health Care Equipment', 'Waltham, Massachusetts', '1985-05-31'),
('BNY Mellon', 'Financials', 'Asset Management & Custody Banks', 'New York City, New York', '1995-03-31'),
('NextEra Energy', 'Utilities', 'Multi-Utilities', 'Juno Beach, Florida', '1976-06-30'),
('Archer Daniels Midland', 'Consumer Staples', 'Agricultural Products & Services', 'Chicago, Illinois', '1957-03-04'),
('Clorox', 'Consumer Staples', 'Household Products', 'Oakland, California', '1969-03-31'),
('United Rentals', 'Industrials', 'Trading Companies & Distributors', 'Stamford, Connecticut', '2014-09-20'),
('Prudential Financial', 'Financials', 'Life & Health Insurance', 'Newark, New Jersey', '2002-07-22'),
('Sherwin-Williams', 'Materials', 'Specialty Chemicals', 'Cleveland, Ohio', '1964-06-30'),
('Uber', 'Industrials', 'Passenger Ground Transportation', 'San Francisco, California', '2023-12-18'),
('Zebra Technologies', 'Information Technology', 'Electronic Equipment & Instruments', 'Lincolnshire, Illinois', '2019-12-23'),
('Fifth Third Bancorp', 'Financials', 'Regional Banks', 'Cincinnati, Ohio', '1996-03-29'),
('Otis Worldwide', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Farmington, Connecticut', '2020-04-03'),
('Truist Financial', 'Financials', 'Diversified Banks', 'Charlotte, North Carolina', '1997-12-04'),
('Sandisk', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'Milpitas, California', '2025-11-28'),
('Comfort Systems USA', 'Industrials', 'Construction & Engineering', 'Houston, Texas', '2025-12-22'),
('Church & Dwight', 'Consumer Staples', 'Household Products', 'Ewing, New Jersey', '2015-12-29'),
('Prologis', 'Real Estate', 'Industrial REITs', 'San Francisco, California', '2003-07-17'),
('Analog Devices', 'Information Technology', 'Semiconductors', 'Wilmington, Massachusetts', '1999-10-12'),
('Kroger', 'Consumer Staples', 'Food Retail', 'Cincinnati, Ohio', '1957-03-04'),
('Take-Two Interactive', 'Communication Services', 'Interactive Home Entertainment', 'New York City, New York', '2018-03-19'),
('Merck & Co.', 'Health Care', 'Pharmaceuticals', 'Kenilworth, New Jersey', '1957-03-04'),
('Ford Motor Company', 'Consumer Discretionary', 'Automobile Manufacturers', 'Dearborn, Michigan', '1957-03-04'),
('Air Products', 'Materials', 'Industrial Gases', 'Upper Macungie Township, Pennsylvania', '1985-04-30'),
('Edwards Lifesciences', 'Health Care', 'Health Care Equipment', 'Irvine, California', '2011-04-01'),
('Raymond James Financial', 'Financials', 'Investment Banking & Brokerage', 'St. Petersburg, Florida', '2017-03-20'),
('Amazon', 'Consumer Discretionary', 'Broadline Retail', 'Seattle, Washington', '2005-11-18'),
('PPG Industries', 'Materials', 'Specialty Chemicals', 'Pittsburgh, Pennsylvania', '1957-03-04'),
('Charter Communications', 'Communication Services', 'Cable & Satellite', 'Stamford, Connecticut', '2016-09-08'),
('Arch Capital Group', 'Financials', 'Property & Casualty Insurance', 'Hamilton, Bermuda', '2022-11-01'),
('ConocoPhillips', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', '1957-03-04'),
('Southern Company', 'Utilities', 'Electric Utilities', 'Atlanta, Georgia', '1957-03-04'),
('CF Industries', 'Materials', 'Fertilizers & Agricultural Chemicals', 'Deerfield, Illinois', '2008-08-27'),
('Lam Research', 'Information Technology', 'Semiconductor Materials & Equipment', 'Fremont, California', '2012-06-29'),
('Corteva', 'Materials', 'Fertilizers & Agricultural Chemicals', 'Indianapolis, Indiana', '2019-06-03'),
('Dexcom', 'Health Care', 'Health Care Equipment', 'San Diego, California', '2020-05-12'),
('NRG Energy', 'Utilities', 'Independent Power Producers & Energy Traders', 'Houston, Texas', '2010-01-29'),
('Moderna', 'Health Care', 'Biotechnology', 'Cambridge, Massachusetts', '2021-07-21'),
('Corpay', 'Financials', 'Transaction & Payment Processing Services', 'Atlanta, Georgia', '2018-06-20'),
('Cboe Global Markets', 'Financials', 'Financial Exchanges & Data', 'Chicago, Illinois', '2017-03-01'),
('IQVIA', 'Health Care', 'Life Sciences Tools & Services', 'Durham, North Carolina', '2017-08-29'),
('Pool Corporation', 'Consumer Discretionary', 'Distributors', 'Covington, Louisiana', '2020-10-07'),
('United Parcel Service', 'Industrials', 'Air Freight & Logistics', 'Sandy Springs, Georgia', '2002-07-22'),
('Western Digital', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'San Jose, California', '2009-07-01'),
('KeyCorp', 'Financials', 'Regional Banks', 'Cleveland, Ohio', '1994-03-01'),
('CBRE Group', 'Real Estate', 'Real Estate Services', 'Dallas, Texas', '2006-11-10'),
('Consolidated Edison', 'Utilities', 'Multi-Utilities', 'New York City, New York', '1957-03-04'),
('CoStar Group', 'Real Estate', 'Real Estate Services', 'Washington, D.C.', '2022-09-19'),
('FirstEnergy', 'Utilities', 'Electric Utilities', 'Akron, Ohio', '1997-11-28'),
('Keysight Technologies', 'Information Technology', 'Electronic Equipment & Instruments', 'Santa Rosa, California', '2018-11-06'),
('Deere & Company', 'Industrials', 'Agricultural & Farm Machinery', 'Moline, Illinois', '1957-03-04'),
('Dayforce', 'Industrials', 'Human Resource & Employment Services', 'Minneapolis, Minnesota', '2021-09-20'),
('Monster Beverage', 'Consumer Staples', 'Soft Drinks & Non-alcoholic Beverages', 'Corona, California', '2012-06-28'),
('Norwegian Cruise Line Holdings', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Miami-Dade County, Florida[4]', '2017-10-13'),
('Emerson Electric', 'Industrials', 'Electrical Components & Equipment', 'Ferguson, Missouri', '1965-03-31'),
('APA Corporation', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', '1997-07-28'),
('Ingersoll Rand', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Davidson, North Carolina', '2020-03-03'),
('Enphase Energy', 'Information Technology', 'Semiconductor Materials & Equipment', 'Fremont, California', '2021-01-07'),
('Corning Inc.', 'Information Technology', 'Electronic Components', 'Corning, New York', '1995-02-27'),
('Qualcomm', 'Information Technology', 'Semiconductors', 'San Diego, California', '1999-07-22'),
('McDonald''s', 'Consumer Discretionary', 'Restaurants', 'Chicago, Illinois', '1970-06-30'),
('Essex Property Trust', 'Real Estate', 'Multi-Family Residential REITs', 'San Mateo, California', '2014-04-02'),
('Carnival', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Miami, Florida', '1998-12-22'),
('Vici Properties', 'Real Estate', 'Hotel & Resort REITs', 'New York City, New York', '2022-06-08'),
('Kraft Heinz', 'Consumer Staples', 'Packaged Foods & Meats', 'Chicago, Illinois;Pittsburgh, Pennsylvania', '2015-07-06'),
('Lowe''s', 'Consumer Discretionary', 'Home Improvement Retail', 'Mooresville, North Carolina', '1984-02-29'),
('Blackstone Inc.', 'Financials', 'Asset Management & Custody Banks', 'New York City, New York', '2023-09-18'),
('Cintas', 'Industrials', 'Diversified Support Services', 'Mason, Ohio', '2001-03-01'),
('General Motors', 'Consumer Discretionary', 'Automobile Manufacturers', 'Detroit, Michigan', '2013-06-06'),
('PepsiCo', 'Consumer Staples', 'Soft Drinks & Non-alcoholic Beverages', 'Purchase, New York', '1957-03-04'),
('Ventas', 'Real Estate', 'Health Care REITs', 'Chicago, Illinois', '2009-03-04'),
('Eaton Corporation', 'Industrials', 'Electrical Components & Equipment', 'Dublin, Ireland', '1957-03-04'),
('IBM', 'Information Technology', 'IT Consulting & Other Services', 'Armonk, New York', '1957-03-04'),
('Wabtec', 'Industrials', 'Construction Machinery & Heavy Transportation Equipment', 'Pittsburgh, Pennsylvania', '2019-02-27'),
('Hologic', 'Health Care', 'Health Care Equipment', 'Marlborough, Massachusetts', '2016-03-30'),
('Huntington Ingalls Industries', 'Industrials', 'Aerospace & Defense', 'Newport News, Virginia', '2018-01-03'),
('ServiceNow', 'Information Technology', 'Systems Software', 'Santa Clara, California', '2019-11-21'),
('Bank of America', 'Financials', 'Diversified Banks', 'Charlotte, North Carolina', '1976-06-30'),
('Home Depot (The)', 'Consumer Discretionary', 'Home Improvement Retail', 'Atlanta, Georgia', '1988-03-31'),
('F5, Inc.', 'Information Technology', 'Communications Equipment', 'Seattle, Washington', '2010-12-20'),
('American Express', 'Financials', 'Consumer Finance', 'New York City, New York', '1976-06-30'),
('McCormick & Company', 'Consumer Staples', 'Packaged Foods & Meats', 'Hunt Valley, Maryland', '2003-03-20'),
('American Tower', 'Real Estate', 'Telecom Tower REITs', 'Boston, Massachusetts', '2007-11-19'),
('SBA Communications', 'Real Estate', 'Telecom Tower REITs', 'Boca Raton, Florida', '2017-09-01'),
('Domino''s', 'Consumer Discretionary', 'Restaurants', 'Ann Arbor, Michigan', '2020-05-12'),
('Huntington Bancshares', 'Financials', 'Regional Banks', 'Columbus, Ohio;Detroit, Michigan', '1997-08-28'),
('AutoZone', 'Consumer Discretionary', 'Automotive Retail', 'Memphis, Tennessee', '1997-01-02'),
('Southwest Airlines', 'Industrials', 'Passenger Airlines', 'Dallas, Texas', '1994-07-01'),
('Capital One', 'Financials', 'Consumer Finance', 'Tysons Corner, Virginia', '1998-07-01'),
('Howmet Aerospace', 'Industrials', 'Aerospace & Defense', 'Pittsburgh, Pennsylvania', '2016-10-21'),
('Berkshire Hathaway', 'Financials', 'Multi-Sector Holdings', 'Omaha, Nebraska', '2010-02-16'),
('Willis Towers Watson', 'Financials', 'Insurance Brokers', 'London, United Kingdom', '2016-01-05'),
('Target Corporation', 'Consumer Staples', 'Consumer Staples Merchandise Retail', 'Minneapolis, Minnesota', '1976-12-31'),
('Eastman Chemical Company', 'Materials', 'Specialty Chemicals', 'Kingsport, Tennessee', '1994-01-01'),
('Phillips 66', 'Energy', 'Oil & Gas Refining & Marketing', 'Houston, Texas', '2012-05-01'),
('MSCI Inc.', 'Financials', 'Financial Exchanges & Data', 'New York City, New York', '2018-04-04'),
('Equifax', 'Industrials', 'Research & Consulting Services', 'Atlanta, Georgia', '1997-06-19'),
('CVS Health', 'Health Care', 'Health Care Services', 'Woonsocket, Rhode Island', '1957-03-04'),
('Synchrony Financial', 'Financials', 'Consumer Finance', 'Stamford, Connecticut', '2015-11-18'),
('ON Semiconductor', 'Information Technology', 'Semiconductors', 'Phoenix, Arizona', '2022-06-21'),
('BlackRock', 'Financials', 'Asset Management & Custody Banks', 'New York City, New York', '2011-04-04'),
('Marriott International', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Bethesda, Maryland', '1998-05-29'),
('Stanley Black & Decker', 'Industrials', 'Industrial Machinery & Supplies & Components', 'New Britain, Connecticut', '1982-09-30'),
('Amgen', 'Health Care', 'Biotechnology', 'Thousand Oaks, California', '1992-01-02'),
('Walt Disney Company (The)', 'Communication Services', 'Movies & Entertainment', 'Burbank, California', '1976-06-30'),
('Steel Dynamics', 'Materials', 'Steel', 'Fort Wayne, Indiana', '2022-12-22'),
('Fidelity National Information Services', 'Financials', 'Transaction & Payment Processing Services', 'Jacksonville, Florida', '2006-11-10'),
('Nucor', 'Materials', 'Steel', 'Charlotte, North Carolina', '1985-04-30'),
('AppLovin', 'Information Technology', 'Application Software', 'Palo Alto, California', '2025-09-22'),
('Charles River Laboratories', 'Health Care', 'Life Sciences Tools & Services', 'Wilmington, Massachusetts', '2021-05-14'),
('Linde plc', 'Materials', 'Industrial Gases', 'Guildford, United Kingdom', '1992-07-01'),
('Palo Alto Networks', 'Information Technology', 'Systems Software', 'Santa Clara, California', '2023-06-20'),
('Welltower', 'Real Estate', 'Health Care REITs', 'Toledo, Ohio', '2009-01-30'),
('Ameren', 'Utilities', 'Multi-Utilities', 'St. Louis, Missouri', '1991-09-19'),
('Texas Pacific Land Corporation', 'Energy', 'Oil & Gas Exploration & Production', 'Dallas, Texas', '2024-11-26'),
('Synopsys', 'Information Technology', 'Application Software', 'Sunnyvale, California', '2017-03-16'),
('Deckers Brands', 'Consumer Discretionary', 'Footwear', 'Goleta, California', '2024-03-18'),
('Procter & Gamble', 'Consumer Staples', 'Personal Care Products', 'Cincinnati, Ohio', '1957-03-04'),
('Ulta Beauty', 'Consumer Discretionary', 'Other Specialty Retail', 'Bolingbrook, Illinois', '2016-04-18'),
('Wells Fargo', 'Financials', 'Diversified Banks', 'San Francisco, California', '1976-06-30'),
('Globe Life', 'Financials', 'Life & Health Insurance', 'McKinney, Texas', '1989-04-30'),
('Palantir Technologies', 'Information Technology', 'Application Software', 'Denver, Colorado', '2024-09-23'),
('Caesars Entertainment', 'Consumer Discretionary', 'Casinos & Gaming', 'Reno, Nevada', '2021-03-22'),
('FactSet', 'Financials', 'Financial Exchanges & Data', 'Norwalk, Connecticut', '2021-12-20'),
('Jacobs Solutions', 'Industrials', 'Construction & Engineering', 'Dallas, Texas', '2007-10-26'),
('Amphenol', 'Information Technology', 'Electronic Components', 'Wallingford, Connecticut', '2008-09-30'),
('Coterra', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', '2008-06-23'),
('Dell Technologies', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'Round Rock, Texas', '2024-09-23'),
('Genuine Parts Company', 'Consumer Discretionary', 'Distributors', 'Atlanta, Georgia', '1973-12-31'),
('Interactive Brokers', 'Financials', 'Investment Banking & Brokerage', 'Greenwich, Connecticut', '2025-08-28'),
('Citigroup', 'Financials', 'Diversified Banks', 'New York City, New York', '1988-05-31'),
('Atmos Energy', 'Utilities', 'Gas Utilities', 'Dallas, Texas', '2019-02-15'),
('Global Payments', 'Financials', 'Transaction & Payment Processing Services', 'Atlanta, Georgia', '2016-04-25'),
('LKQ Corporation', 'Consumer Discretionary', 'Distributors', 'Nashville, Tennessee', '2016-05-23'),
('Gen Digital', 'Information Technology', 'Systems Software', 'Tempe, Arizona', '2003-03-25'),
('Smurfit Westrock', 'Materials', 'Paper & Plastic Packaging Products & Materials', 'Dublin, Ireland', '2024-07-08'),
('Trimble Inc.', 'Information Technology', 'Electronic Equipment & Instruments', 'Westminster, Colorado', '2021-01-21'),
('International Flavors & Fragrances', 'Materials', 'Specialty Chemicals', 'New York City, New York', '1976-03-31'),
('Teradyne', 'Information Technology', 'Semiconductor Materials & Equipment', 'North Reading, Massachusetts', '2020-09-21'),
('Gilead Sciences', 'Health Care', 'Biotechnology', 'Foster City, California', '2004-07-01'),
('Norfolk Southern', 'Industrials', 'Rail Transportation', 'Atlanta, Georgia', '1957-03-04'),
('Biogen', 'Health Care', 'Biotechnology', 'Cambridge, Massachusetts', '2003-11-13'),
('Darden Restaurants', 'Consumer Discretionary', 'Restaurants', 'Orlando, Florida', '1995-05-31'),
('PTC Inc.', 'Information Technology', 'Application Software', 'Boston, Massachusetts', '2021-04-20'),
('Workday, Inc.', 'Information Technology', 'Application Software', 'Pleasanton, California', '2024-12-23'),
('Progressive Corporation', 'Financials', 'Property & Casualty Insurance', 'Mayfield Village, Ohio', '1997-08-04'),
('Williams Companies', 'Energy', 'Oil & Gas Storage & Transportation', 'Tulsa, Oklahoma', '1975-03-31'),
('Intuitive Surgical', 'Health Care', 'Health Care Equipment', 'Sunnyvale, California', '2008-06-02'),
('Pfizer', 'Health Care', 'Pharmaceuticals', 'New York City, New York', '1957-03-04'),
('Xylem Inc.', 'Industrials', 'Industrial Machinery & Supplies & Components', 'White Plains, New York', '2011-11-01'),
('Rockwell Automation', 'Industrials', 'Electrical Components & Equipment', 'Milwaukee, Wisconsin', '2000-03-12'),
('Snap-on', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Kenosha, Wisconsin', '1982-09-30'),
('Baker Hughes', 'Energy', 'Oil & Gas Equipment & Services', 'Houston, Texas', '2017-07-07'),
('Electronic Arts', 'Communication Services', 'Interactive Home Entertainment', 'Redwood City, California', '2002-07-22'),
('Danaher Corporation', 'Health Care', 'Life Sciences Tools & Services', 'Washington, D.C.', '1998-11-18'),
('Trane Technologies', 'Industrials', 'Building Products', 'Dublin, Ireland', '2010-11-17'),
('FedEx', 'Industrials', 'Air Freight & Logistics', 'Memphis, Tennessee', '1980-12-31'),
('Citizens Financial Group', 'Financials', 'Regional Banks', 'Providence, Rhode Island', '2016-01-29'),
('Best Buy', 'Consumer Discretionary', 'Computer & Electronics Retail', 'Richfield, Minnesota', '1999-06-29'),
('Alliant Energy', 'Utilities', 'Electric Utilities', 'Madison, Wisconsin', '2016-07-01'),
('NVR, Inc.', 'Consumer Discretionary', 'Homebuilding', 'Reston, Virginia', '2019-09-26'),
('BXP, Inc.', 'Real Estate', 'Office REITs', 'Boston, Massachusetts', '2006-04-03'),
('Dow Inc.', 'Materials', 'Commodity Chemicals', 'Midland, Michigan', '2019-04-01'),
('Expand Energy', 'Energy', 'Oil & Gas Exploration & Production', 'Oklahoma City, Oklahoma', '2025-03-24'),
('Alexandria Real Estate Equities', 'Real Estate', 'Office REITs', 'Pasadena, California', '2017-03-20'),
('Broadcom', 'Information Technology', 'Semiconductors', 'Palo Alto, California', '2014-05-08'),
('Kimberly-Clark', 'Consumer Staples', 'Household Products', 'Irving, Texas', '1957-03-04'),
('McKesson Corporation', 'Health Care', 'Health Care Distributors', 'Irving, Texas', '1999-01-13'),
('Mid-America Apartment Communities', 'Real Estate', 'Multi-Family Residential REITs', 'Memphis, Tennessee', '2016-12-02'),
('Constellation Brands', 'Consumer Staples', 'Distillers & Vintners', 'Rochester, New York', '2005-07-01'),
('Molina Healthcare', 'Health Care', 'Managed Health Care', 'Long Beach, California', '2022-03-02'),
('Parker Hannifin', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Cleveland, Ohio', '1985-11-30'),
('Healthpeak Properties', 'Real Estate', 'Health Care REITs', 'Denver, Colorado', '2008-03-31'),
('MetLife', 'Financials', 'Life & Health Insurance', 'New York City, New York', '2000-12-11'),
('PayPal', 'Financials', 'Transaction & Payment Processing Services', 'San Jose, California', '2015-07-20'),
('Halliburton', 'Energy', 'Oil & Gas Equipment & Services', 'Houston, Texas', '1957-03-04'),
('Align Technology', 'Health Care', 'Health Care Supplies', 'Tempe, Arizona', '2017-06-19'),
('Extra Space Storage', 'Real Estate', 'Self-Storage REITs', 'Salt Lake City, Utah', '2016-01-19'),
('Erie Indemnity', 'Financials', 'Insurance Brokers', 'Erie, Pennsylvania', '2024-09-23'),
('Waters Corporation', 'Health Care', 'Life Sciences Tools & Services', 'Milford, Massachusetts', '2002-01-02'),
('Xcel Energy', 'Utilities', 'Multi-Utilities', 'Minneapolis, Minnesota', '1957-03-04'),
('TKO Group Holdings', 'Communication Services', 'Movies & Entertainment', 'New York City, New York', '2025-03-24'),
('Estée Lauder Companies (The)', 'Consumer Staples', 'Personal Care Products', 'New York City, New York', '2006-01-05'),
('Dollar General', 'Consumer Staples', 'Consumer Staples Merchandise Retail', 'Goodlettsville, Tennessee', '2012-12-03'),
('Equity Residential', 'Real Estate', 'Multi-Family Residential REITs', 'Chicago, Illinois', '2001-12-03'),
('NetApp', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'San Jose, California', '1999-06-25'),
('D. R. Horton', 'Consumer Discretionary', 'Homebuilding', 'Arlington, Texas', '2005-06-22'),
('Yum! Brands', 'Consumer Discretionary', 'Restaurants', 'Louisville, Kentucky', '1997-10-06'),
('Nasdaq, Inc.', 'Financials', 'Financial Exchanges & Data', 'New York City, New York', '2008-10-22'),
('Vulcan Materials Company', 'Materials', 'Construction Materials', 'Birmingham, Alabama', '1999-06-30'),
('Teledyne Technologies', 'Information Technology', 'Electronic Equipment & Instruments', 'Thousand Oaks, California', '2020-06-22'),
('Devon Energy', 'Energy', 'Oil & Gas Exploration & Production', 'Oklahoma City, Oklahoma', '2000-08-30'),
('Regions Financial Corporation', 'Financials', 'Regional Banks', 'Birmingham, Alabama', '1998-08-28'),
('International Paper', 'Materials', 'Paper & Plastic Packaging Products & Materials', 'Memphis, Tennessee', '1957-03-04'),
('State Street Corporation', 'Financials', 'Asset Management & Custody Banks', 'Boston, Massachusetts', '2003-03-14'),
('Loews Corporation', 'Financials', 'Multi-line Insurance', 'New York City, New York', '1995-05-31'),
('United Airlines Holdings', 'Industrials', 'Passenger Airlines', 'Chicago, Illinois', '2015-09-03'),
('Ares Management', 'Financials', 'Asset Management & Custody Banks', 'Los Angeles, California', '2025-12-11'),
('Textron', 'Industrials', 'Aerospace & Defense', 'Providence, Rhode Island', '1978-12-31'),
('Starbucks', 'Consumer Discretionary', 'Restaurants', 'Seattle, Washington', '2000-06-07'),
('NXP Semiconductors', 'Information Technology', 'Semiconductors', 'Eindhoven, Netherlands', '2021-03-22'),
('T-Mobile US', 'Communication Services', 'Wireless Telecommunication Services', 'Bellevue, Washington', '2019-07-15'),
('Northern Trust', 'Financials', 'Asset Management & Custody Banks', 'Chicago, Illinois', '1998-01-30'),
('Realty Income', 'Real Estate', 'Retail REITs', 'San Diego, California', '2015-04-07'),
('Oracle Corporation', 'Information Technology', 'Application Software', 'Austin, Texas', '1989-08-31'),
('General Mills', 'Consumer Staples', 'Packaged Foods & Meats', 'Golden Valley, Minnesota', '1957-03-04'),
('Vistra Corp.', 'Utilities', 'Electric Utilities', 'Irving, Texas', '2024-05-08'),
('Alphabet Inc.(Class A)', 'Communication Services', 'Interactive Media & Services', 'Mountain View, California', '2006-04-03'),
('Block, Inc.', 'Financials', 'Transaction & Payment Processing Services', 'none', '2025-07-23'),
('Chipotle Mexican Grill', 'Consumer Discretionary', 'Restaurants', 'Newport Beach, California', '2011-04-28'),
('Tyler Technologies', 'Information Technology', 'Application Software', 'Plano, Texas', '2020-06-22'),
('AvalonBay Communities', 'Real Estate', 'Multi-Family Residential REITs', 'Arlington, Virginia', '2007-01-10'),
('Johnson Controls', 'Industrials', 'Building Products', 'Cork, Ireland', '2010-08-27'),
('Moody''s Corporation', 'Financials', 'Financial Exchanges & Data', 'New York City, New York', '1998-07-01'),
('Zoetis', 'Health Care', 'Pharmaceuticals', 'Parsippany, New Jersey', '2013-06-21'),
('EPAM Systems', 'Information Technology', 'IT Consulting & Other Services', 'Newtown, Pennsylvania', '2021-12-14'),
('Alphabet Inc.(Class C)', 'Communication Services', 'Interactive Media & Services', 'Mountain View, California', '2014-04-03'),
('Illinois Tool Works', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Glenview, Illinois', '1986-02-28'),
('Union Pacific Corporation', 'Industrials', 'Rail Transportation', 'Omaha, Nebraska', '1957-03-04'),
('Cigna', 'Health Care', 'Health Care Services', 'Bloomfield, Connecticut', '1976-06-30'),
('Royal Caribbean Group', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Miami, Florida', '2014-12-05'),
('T. Rowe Price', 'Financials', 'Asset Management & Custody Banks', 'Baltimore, Maryland', '2019-07-29'),
('Netflix', 'Communication Services', 'Movies & Entertainment', 'Los Gatos, California', '2010-12-20'),
('Insulet Corporation', 'Health Care', 'Health Care Equipment', 'Acton, Massachusetts', '2023-03-15'),
('Autodesk', 'Information Technology', 'Application Software', 'San Francisco, California', '1989-12-01'),
('Verisign', 'Information Technology', 'Internet Services & Infrastructure', 'Reston, Virginia', '2006-02-01'),
('Rollins, Inc.', 'Industrials', 'Environmental & Facilities Services', 'Atlanta, Georgia', '2018-10-01'),
('Martin Marietta Materials', 'Materials', 'Construction Materials', 'Raleigh, North Carolina', '2014-07-02'),
('Ametek', 'Industrials', 'Electrical Components & Equipment', 'Berwyn, Pennsylvania', '2013-09-23'),
('Morgan Stanley', 'Financials', 'Investment Banking & Brokerage', 'New York City, New York', '1993-07-29'),
('GoDaddy', 'Information Technology', 'Internet Services & Infrastructure', 'Tempe, Arizona', '2024-06-24'),
('News Corp(Class A)', 'Communication Services', 'Publishing', 'New York City, New York', '2013-08-01'),
('Applied Materials', 'Information Technology', 'Semiconductor Materials & Equipment', 'Santa Clara, California', '1995-03-16'),
('Cognizant', 'Information Technology', 'IT Consulting & Other Services', 'Teaneck, New Jersey', '2006-11-17'),
('Caterpillar Inc.', 'Industrials', 'Construction Machinery & Heavy Transportation Equipment', 'Irving, Texas', '1957-03-04'),
('Fortive', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Everett, Washington', '2016-07-01'),
('West Pharmaceutical Services', 'Health Care', 'Health Care Supplies', 'Exton, Pennsylvania', '2020-05-22'),
('GE Vernova', 'Industrials', 'Heavy Electrical Equipment', 'Cambridge, Massachusetts', '2024-04-02'),
('Coca-Cola Company (The)', 'Consumer Staples', 'Soft Drinks & Non-alcoholic Beverages', 'Atlanta, Georgia', '1957-03-04'),
('Advanced Micro Devices', 'Information Technology', 'Semiconductors', 'Santa Clara, California', '2017-03-20'),
('Camden Property Trust', 'Real Estate', 'Multi-Family Residential REITs', 'Houston, Texas', '2022-04-04'),
('Ecolab', 'Materials', 'Specialty Chemicals', 'Saint Paul, Minnesota', '1989-01-31'),
('IDEX Corporation', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Northbrook, Illinois', '2019-08-09'),
('Nike, Inc.', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Washington County, Oregon', '1988-11-30'),
('A. O. Smith', 'Industrials', 'Building Products', 'Milwaukee, Wisconsin', '2017-07-26'),
('Allegion', 'Industrials', 'Building Products', 'Dublin, Ireland', '2013-12-02'),
('J.M. Smucker Company (The)', 'Consumer Staples', 'Packaged Foods & Meats', 'Orrville, Ohio', '2008-11-06'),
('Paychex', 'Industrials', 'Human Resource & Employment Services', 'Penfield, New York', '1998-10-01'),
('Accenture', 'Information Technology', 'IT Consulting & Other Services', 'Dublin, Ireland', '2011-07-06'),
('Kellanov', 'Consumer Staples', 'Packaged Foods & Meats', 'Chicago, Illinois', '1989-09-11'),
('Datadog', 'Information Technology', 'Application Software', 'New York City, New York', '2025-07-09'),
('Sysco', 'Consumer Staples', 'Food Distributors', 'Houston, Texas', '1986-12-31'),
('Coinbase', 'Financials', 'Financial Exchanges & Data', 'New York City, New York', '2025-05-19'),
('Roper Technologies', 'Information Technology', 'Electronic Equipment & Instruments', 'Sarasota, Florida', '2009-12-23'),
('EOG Resources', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', '2000-11-02'),
('Apple Inc.', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'Cupertino, California', '1982-11-30'),
('PulteGroup', 'Consumer Discretionary', 'Homebuilding', 'Atlanta, Georgia', '1984-04-30'),
('Lamb Weston', 'Consumer Staples', 'Packaged Foods & Meats', 'Eagle, Idaho', '2018-12-03'),
('Travelers Companies (The)', 'Financials', 'Property & Casualty Insurance', 'New York City, New York', '2002-08-21'),
('American International Group', 'Financials', 'Multi-line Insurance', 'New York City, New York', '1980-03-31'),
('Comcast', 'Communication Services', 'Cable & Satellite', 'Philadelphia, Pennsylvania', '2002-11-19'),
('CarMax', 'Consumer Discretionary', 'Automotive Retail', 'Richmond, Virginia', '2010-06-28'),
('Bio-Techne', 'Health Care', 'Life Sciences Tools & Services', 'Minneapolis, Minnesota', '2021-08-30'),
('Paccar', 'Industrials', 'Construction Machinery & Heavy Transportation Equipment', 'Bellevue, Washington', '1980-12-31'),
('Hilton Worldwide', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Tysons Corner, Virginia', '2017-06-19'),
('Expedia Group', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Seattle, Washington', '2007-10-02'),
('TJX Companies', 'Consumer Discretionary', 'Apparel Retail', 'Framingham, Massachusetts', '1985-09-30'),
('Texas Instruments', 'Information Technology', 'Semiconductors', 'Dallas, Texas', '2001-03-12'),
('RTX Corporation', 'Industrials', 'Aerospace & Defense', 'Waltham, Massachusetts', '1957-03-04'),
('Wynn Resorts', 'Consumer Discretionary', 'Casinos & Gaming', 'Paradise, Nevada', '2008-11-14'),
('Cadence Design Systems', 'Information Technology', 'Application Software', 'San Jose, California', '2017-09-18'),
('UDR, Inc.', 'Real Estate', 'Multi-Family Residential REITs', 'Highlands Ranch, Colorado', '2016-03-07'),
('Fox Corporation(Class A)', 'Communication Services', 'Broadcasting', 'New York City, New York', '2019-03-19'),
('Mastercard', 'Financials', 'Transaction & Payment Processing Services', 'Harrison, New York', '2008-07-18'),
('Live Nation Entertainment', 'Communication Services', 'Movies & Entertainment', 'Beverly Hills, California', '2019-12-23'),
('Medtronic', 'Health Care', 'Health Care Equipment', 'Dublin, Ireland', '1986-10-31'),
('Chevron Corporation', 'Energy', 'Integrated Oil & Gas', 'Houston, Texas', '1957-03-04'),
('Old Dominion', 'Industrials', 'Cargo Ground Transportation', 'Thomasville, North Carolina', '2019-12-09'),
('News Corp(Class B)', 'Communication Services', 'Publishing', 'New York City, New York', '2015-09-18'),
('GE HealthCare', 'Health Care', 'Health Care Equipment', 'Chicago, Illinois', '2023-01-04'),
('MarketAxess', 'Financials', 'Financial Exchanges & Data', 'New York City, New York', '2019-07-01'),
('JPMorgan Chase', 'Financials', 'Diversified Banks', 'New York City, New York', '1975-06-30'),
('CMS Energy', 'Utilities', 'Multi-Utilities', 'Jackson, Michigan', '1957-03-04'),
('Bristol Myers Squibb', 'Health Care', 'Pharmaceuticals', 'New York City, New York', '1957-03-04'),
('Jack Henry & Associates', 'Financials', 'Transaction & Payment Processing Services', 'Monett, Missouri', '2018-11-13'),
('Weyerhaeuser', 'Real Estate', 'Timber REITs', 'Seattle, Washington', '1979-10-01'),
('MGM Resorts', 'Consumer Discretionary', 'Casinos & Gaming', 'Paradise, Nevada', '2017-07-26'),
('Public Service Enterprise Group', 'Utilities', 'Electric Utilities', 'Newark, New Jersey', '1957-03-04'),
('Aflac', 'Financials', 'Life & Health Insurance', 'Columbus, Georgia', '1999-05-28'),
('Brown & Brown', 'Financials', 'Insurance Brokers', 'Daytona Beach, Florida', '2021-09-20'),
('Everest Group', 'Financials', 'Reinsurance', 'Hamilton, Bermuda', '2017-06-19'),
('Supermicro', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'San Jose, California', '2024-03-18'),
('Booking Holdings', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Norwalk, Connecticut', '2009-11-06'),
('Invesco', 'Financials', 'Asset Management & Custody Banks', 'Atlanta, Georgia', '2008-08-21'),
('Microchip Technology', 'Information Technology', 'Semiconductors', 'Chandler, Arizona', '2007-09-07'),
('Monolithic Power Systems', 'Information Technology', 'Semiconductors', 'Kirkland, Washington', '2021-02-12'),
('Omnicom Group', 'Communication Services', 'Advertising', 'New York City, New York', '1997-12-31'),
('C.H. Robinson', 'Industrials', 'Air Freight & Logistics', 'Eden Prairie, Minnesota', '2007-03-02'),
('American Water Works', 'Utilities', 'Water Utilities', 'Camden, New Jersey', '2016-03-04'),
('Arista Networks', 'Information Technology', 'Communications Equipment', 'Santa Clara, California', '2018-08-28'),
('Becton Dickinson', 'Health Care', 'Health Care Equipment', 'Franklin Lakes, New Jersey', '1972-09-30'),
('CDW Corporation', 'Information Technology', 'Technology Distributors', 'Vernon Hills, Illinois', '2019-09-23'),
('Micron Technology', 'Information Technology', 'Semiconductors', 'Boise, Idaho', '1994-09-27'),
('Eversource Energy', 'Utilities', 'Electric Utilities', 'Hartford, Connecticut', '2009-07-24'),
('Builders FirstSource', 'Industrials', 'Building Products', 'Irving, Texas', '2023-12-18'),
('WEC Energy Group', 'Utilities', 'Electric Utilities', 'Milwaukee, Wisconsin', '2008-10-31'),
('Newmont', 'Materials', 'Gold', 'Denver, Colorado', '1969-06-30'),
('Abbott Laboratories', 'Health Care', 'Health Care Equipment', 'North Chicago, Illinois', '1957-03-04'),
('Lilly (Eli)', 'Health Care', 'Pharmaceuticals', 'Indianapolis, Indiana', '1970-12-31'),
('Emcor', 'Industrials', 'Construction & Engineering', 'Norwalk, Connecticut', '2025-09-22'),
('Franklin Resources', 'Financials', 'Asset Management & Custody Banks', 'San Mateo, California', '1998-04-30'),
('CenterPoint Energy', 'Utilities', 'Multi-Utilities', 'Houston, Texas', '1985-07-31'),
('American Electric Power', 'Utilities', 'Electric Utilities', 'Columbus, Ohio', '1957-03-04'),
('Paramount Global', 'Communication Services', 'Movies & Entertainment', 'New York City, New York', '1994-09-30'),
('Crown Castle', 'Real Estate', 'Telecom Tower REITs', 'Houston, Texas', '2012-03-14'),
('Expeditors International', 'Industrials', 'Air Freight & Logistics', 'Seattle, Washington', '2007-10-10'),
('J.B. Hunt', 'Industrials', 'Cargo Ground Transportation', 'Lowell, Arkansas', '2015-07-01'),
('Dominion Energy', 'Utilities', 'Multi-Utilities', 'Richmond, Virginia', '2016-11-30'),
('Dollar Tree', 'Consumer Staples', 'Consumer Staples Merchandise Retail', 'Chesapeake, Virginia', '2011-12-19'),
('DTE Energy', 'Utilities', 'Multi-Utilities', 'Detroit, Michigan', '1957-03-04'),
('Hewlett Packard Enterprise', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'Houston, Texas', '2015-11-02'),
('Williams-Sonoma, Inc.', 'Consumer Discretionary', 'Homefurnishing Retail', 'San Francisco, California', '2025-03-24'),
('Mettler Toledo', 'Health Care', 'Life Sciences Tools & Services', 'Columbus, Ohio', '2016-09-06'),
('Viatris', 'Health Care', 'Pharmaceuticals', 'Pittsburgh, Pennsylvania', '2004-04-23'),
('Goldman Sachs', 'Financials', 'Investment Banking & Brokerage', 'New York City, New York', '2002-07-22'),
('Las Vegas Sands', 'Consumer Discretionary', 'Casinos & Gaming', 'Las Vegas, Nevada', '2019-10-03'),
('Oneok', 'Energy', 'Oil & Gas Storage & Transportation', 'Tulsa, Oklahoma', '2010-03-15'),
('Microsoft', 'Information Technology', 'Systems Software', 'Redmond, Washington', '1994-06-01'),
('L3Harris', 'Industrials', 'Aerospace & Defense', 'Melbourne, Florida', '2008-09-22'),
('Steris', 'Health Care', 'Health Care Equipment', 'Dublin, Ireland', '2019-12-23'),
('First Solar', 'Information Technology', 'Semiconductors', 'Tempe, Arizona', '2022-12-19'),
('Hartford (The)', 'Financials', 'Property & Casualty Insurance', 'Hartford, Connecticut', '1957-03-04'),
('Invitation Homes', 'Real Estate', 'Single-Family Residential REITs', 'Dallas, Texas', '2022-09-19'),
('Lockheed Martin', 'Industrials', 'Aerospace & Defense', 'Bethesda, Maryland', '1957-03-04'),
('Zimmer Biomet', 'Health Care', 'Health Care Equipment', 'Warsaw, Indiana', '2001-08-07'),
('Masco', 'Industrials', 'Building Products', 'Livonia, Michigan', '1981-06-30'),
('Airbnb', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'San Francisco, California', '2023-09-18'),
('Visa Inc.', 'Financials', 'Transaction & Payment Processing Services', 'San Francisco, California', '2009-12-21'),
('Copart', 'Industrials', 'Diversified Support Services', 'Dallas, Texas', '2018-07-02'),
('Avery Dennison', 'Materials', 'Paper & Plastic Packaging Products & Materials', 'Mentor, Ohio', '1987-12-31'),
('Boston Scientific', 'Health Care', 'Health Care Equipment', 'Marlborough, Massachusetts', '1995-02-24'),
('Edison International', 'Utilities', 'Electric Utilities', 'Rosemead, California', '1957-03-04'),
('PNC Financial Services', 'Financials', 'Diversified Banks', 'Pittsburgh, Pennsylvania', '1988-04-30'),
('Pentair', 'Industrials', 'Industrial Machinery & Supplies & Components', 'Worsley, United Kingdom', '2012-10-01'),
('Keurig Dr Pepper', 'Consumer Staples', 'Soft Drinks & Non-alcoholic Beverages', 'Burlington, Massachusetts', '2022-06-21'),
('Brown–Forman', 'Consumer Staples', 'Distillers & Vintners', 'Louisville, Kentucky', '1982-10-31'),
('Simon Property Group', 'Real Estate', 'Retail REITs', 'Indianapolis, Indiana', '2002-06-26'),
('Apollo Global Management', 'Financials', 'Asset Management & Custody Banks', 'New York City, New York', '2024-12-23'),
('Seagate Technology', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'Dublin, Ireland', '2012-07-02'),
('Cardinal Health', 'Health Care', 'Health Care Distributors', 'Dublin, Ohio', '1997-05-27'),
('Waste Management', 'Industrials', 'Environmental & Facilities Services', 'Houston, Texas', '1998-08-31'),
('Intuit', 'Information Technology', 'Application Software', 'Mountain View, California', '2000-12-05'),
('Tractor Supply', 'Consumer Discretionary', 'Other Specialty Retail', 'Brentwood, Tennessee', '2014-01-24'),
('Labcorp', 'Health Care', 'Health Care Services', 'Burlington, North Carolina', '2004-11-01'),
('Aon plc', 'Financials', 'Insurance Brokers', 'London, United Kingdom', '1996-04-23'),
('Tapestry, Inc.', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York City, New York', '2004-09-01'),
('Cencora', 'Health Care', 'Health Care Distributors', 'Conshohocken, Pennsylvania', '2001-08-30'),
('Equinix', 'Real Estate', 'Data Center REITs', 'Redwood City, California', '2015-03-20'),
('Assurant', 'Financials', 'Multi-line Insurance', 'Atlanta, Georgia', '2007-04-10'),
('Campbell''s Company (The)', 'Consumer Staples', 'Packaged Foods & Meats', 'Camden, New Jersey', '1957-03-04'),
('Baxter International', 'Health Care', 'Health Care Equipment', 'Deerfield, Illinois', '1972-09-30'),
('S&P Global', 'Financials', 'Financial Exchanges & Data', 'New York City, New York', '1957-03-04'),
('Marathon Petroleum', 'Energy', 'Oil & Gas Refining & Marketing', 'Findlay, Ohio', '2011-07-01'),
('Kinder Morgan', 'Energy', 'Oil & Gas Storage & Transportation', 'Houston, Texas', '2012-05-25'),
('U.S. Bancorp', 'Financials', 'Diversified Banks', 'Minneapolis, Minnesota', '1999-11-01');
